import {blankAnswers,chosenObjects,SOURCE_NAMES,TRIGGERS,setupSteps,makeJourneyPlan,planText} from './journey-model.mjs';
import {createWorld} from './journey-visuals.mjs';
const $=id=>document.getElementById(id), node=(tag,value,cls)=>{const n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(cls)n.className=cls;return n;};
const data=await fetch('./journeys.json').then(r=>{if(!r.ok)throw Error('场景资料未加载');return r.json();});
let scene,answers,current=0,paused=matchMedia('(prefers-reduced-motion:reduce)').matches,noticeTimer;
const cleanup=new Map();const total=15;const progress=node('div',undefined,'step-track');document.querySelector('header').append(progress);
function scrollTo(n){n.scrollIntoView({block:'start',behavior:paused?'instant':'smooth'});}
function notify(s){$('status').textContent=s;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('status').textContent='',2800);}
const observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.target.isConnected&&e.isIntersecting&&e.intersectionRatio>.35){const i=Number(e.target.dataset.step||0);$('position').textContent=i?`${String(i).padStart(2,'0')} / ${total} · ${e.target.dataset.label}`:'从一个想法开始';progress.style.setProperty('--progress',`${i/total*100}%`);}}},{threshold:[.35,.6]});observer.observe($('welcome'));
function discardAfter(i){document.querySelectorAll('.guided-step').forEach(s=>{if(Number(s.dataset.step)>i){cleanup.get(s)?.();cleanup.delete(s);observer.unobserve(s);s.remove();}});}
function action(host,label,fn,{cue='点这里，继续下一步',secondary=false}={}){if(cue)host.append(node('div','↓ '+cue,'cue'));const b=node('button',label,secondary?'secondary':'primary spotlight');b.type='button';b.onclick=fn;host.append(b);return b;}
function page(i,label,title,description,render){discardAfter(i-1);current=i;$('position').textContent=`${String(i).padStart(2,'0')} / ${total} · ${label}`;progress.style.setProperty('--progress',`${i/total*100}%`);document.querySelectorAll('.guided-step').forEach(s=>s.classList.add('past'));const s=node('section',undefined,'screen guided-step');s.id=`step-${i}`;s.dataset.step=i;s.dataset.label=label;const body=node('div',undefined,'page-content');s.append(body);body.append(node('p',`第 ${String(i).padStart(2,'0')} 步 · ${label}`,'eyebrow'),node('h2',title));if(description)body.append(node('p',description,'lead'));render(body,s);if(i>1){const back=node('div',undefined,'page-back');const b=node('button','↑ 回到上一步修改');b.onclick=()=>scrollTo($(`step-${i-1}`));back.append(b);body.append(back);} $('pages').append(s);observer.observe(s);scrollTo(s);const heading=body.querySelector('h2');heading.tabIndex=-1;heading.focus({preventScroll:true});}
function options(body,values,select){body.append(node('div','↓ 点击最符合你想法的一项','cue'));const list=node('div',undefined,'choices');values.forEach(([v,label],i)=>{const b=node('button',undefined,'choice');b.type='button';b.dataset.value=v;b.append(node('span',String(i+1).padStart(2,'0'),'number'),node('span',label,'label'),node('span','↓','arrow'));b.onclick=()=>{list.querySelectorAll('button').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',String(n===b));});select(v);};list.append(b);});body.append(list);}
function select(id){clearTimeout(noticeTimer);$('status').textContent='';scene=data.scenes.find(s=>s.id===+id);if(!scene)return;answers=blankAnswers(scene);discardAfter(0);$('library').classList.remove('open');history.replaceState(null,'',`#scene-${String(id).padStart(2,'0')}`);focus();}
function focus(){page(1,'说清想法',scene.question,'你刚才说：“'+scene.thought+'”。先选出最想解决的部分。',body=>options(body,scene.choices.map((c,i)=>[i,c.label]),v=>{answers.focus=+v;detail();}));}
function detail(){page(2,'确认做法',scene.detailQuestion,'再确认一件事，昭回才知道按什么方式处理。',body=>options(body,scene.details.map((v,i)=>[i,v]),v=>{answers.detail=+v;source();}));}
function source(){page(3,'安排资料','这些资料从哪里来？','这项工作会用到：'+scene.source+'。连接资料也在这里一起完成。',body=>options(body,Object.entries(SOURCE_NAMES),v=>{answers.source=v;answers.connectionConfirmed=false;sample();}));}
function sample(){page(4,'连接与确认','先认准这家店，再查看资料','真实使用时，昭回会引导你确认账号和读取范围。这里先走一遍示例。',(body)=>{
const label=node('label','选择这份资料所属的平台');const sel=node('select');sel.id='shop';scene.platforms.forEach(p=>{const opt=node('option',p);opt.value=p;sel.append(opt);});sel.value=answers.shop;label.append(sel);body.append(label);
const visual=node('div',undefined,'visual-demo');const flow=node('div',undefined,'connect-flow');flow.append(node('div',answers.source==='files'?'资料':'店铺','app-icon'));const dots=node('div',undefined,'moving-dots');for(let i=0;i<3;i++)dots.append(node('i'));flow.append(dots,node('div','昭回','app-icon destination'));visual.append(flow);body.append(visual);
const result=node('div',undefined,'sample-list');result.hidden=true;visual.append(result);let loaded=false;
const b=action(body,'点击，查看示例资料',()=>{if(!loaded){answers.shop=sel.value;sel.disabled=true;chosenObjects(scene,answers).forEach(x=>{const p=node('p',x.title);p.append(node('small',x.before));result.append(p);});result.hidden=false;loaded=true;b.textContent='确认是这份资料，继续 ↓';body.querySelector('.cue').textContent='↓ 核对上面的内容，再点这里确认';}else{answers.connectionConfirmed=true;trigger();}},{cue:'点这里，看看连接后拿到什么'});});}
function trigger(){page(5,'安排开始时间','希望它什么时候开始？','可以到时间自动检查，也可以由你在聊天里交办。',body=>{const label=node('label','如果选择定时，每天几点检查？（北京时间）');const time=node('input');time.type='time';time.value=answers.time;time.id='time';label.append(time);body.append(label);options(body,Object.entries(TRIGGERS).map(([k,v])=>[k,v.label]),v=>{if(v==='clock'&&!time.value){time.reportValidity();return;}answers.time=time.value||'09:00';answers.trigger=v;delivery();});});}
function delivery(){page(6,'确定结果','处理完，想怎样查看？','先决定你希望收到什么，不必研究后台设置。',body=>options(body,[['brief','直接给我待处理清单'],['explained','也告诉我原因和原来的情况']],v=>{answers.delivery=v;review();}));}
function review(){page(7,'确认安排','这就是我们刚才说好的工作','检查一遍，下面开始演示昭回怎样搭建。',body=>{const list=node('div',undefined,'result-cards');for(const [k,v]of [['重点',scene.choices[answers.focus].label],['方式',scene.details[answers.detail]],['资料',SOURCE_NAMES[answers.source]+' · '+answers.shop],['开始',TRIGGERS[answers.trigger].label+(answers.trigger==='clock'?'，每天 '+answers.time:'')]]){const item=node('article');item.append(node('b',k),node('p',v));list.append(item);}body.append(list);action(body,'确认安排，开始搭建 ↓',()=>buildPage(0),{cue:'这些符合你的想法，就点这里'});});}
function buildPage(n){const steps=setupSteps(scene,answers);const pairs=[[0,1],[2,3],[4,5]], titles=['先接好资料，记住你的要求','把具体处理步骤保存下来','安排开始条件，准备试一次'];page(8+n,'搭建中',titles[n],'你不需要画流程图。昭回根据刚才的回答准备这部分。',body=>{const visual=node('div',undefined,'visual-demo');visual.append(node('div',['◉','▤','◷'][n],'build-icon'),node('p',[SOURCE_NAMES[answers.source],scene.steps.join(' → '),TRIGGERS[answers.trigger].label][n],'build-summary'));for(const j of pairs[n]){const p=node('p',steps[j].result,'build-caption');visual.append(p);}body.append(visual);const detail=node('details');detail.append(node('summary','想知道实际怎样完成？'));for(const j of pairs[n])detail.append(node('p',steps[j].ai,'small'));body.append(detail);action(body,n===2?'准备好了，试一次 ↓':'这一步明白了，继续 ↓',()=>n<2?buildPage(n+1):start(),{cue:n===2?'点这里，进入运行演示':'点这里，继续看下一步怎样搭建'});});}
function start(){page(11,'触发一次',answers.trigger==='clock'?'时间到了，它就开始工作':answers.trigger==='chat'?'在聊天里，把这件事交给昭回':'资料更新了，它就开始检查','下面只模拟一次开始动作，看看后面会发生什么。',body=>{const demo=node('div',undefined,'visual-demo');demo.append(node('div',{clock:'◷',chat:'✉',file:'▤'}[answers.trigger],'build-icon'),node('p',answers.trigger==='clock'?`每天 ${answers.time}`:answers.trigger==='chat'?scene.thought:scene.source,'build-summary'));body.append(demo);action(body,TRIGGERS[answers.trigger].action+' ↓',()=>runPage(0),{cue:'点这里，亲自触发这次演示'});});}
function runPage(n){const frame=n===0?1:3;page(12+n,'正在处理',n===0?'先取出这次要检查的资料':scene.steps[1],n===0?'只查看刚才约定的范围，先确认资料是否正确。':scene.steps[0]+'。处理后的变化会显示在每条记录里。',(body,section)=>{section.classList.add('run-screen');const host=node('div');body.append(host);const world=createWorld(host,scene);const config={indices:chosenObjects(scene,answers).map(x=>x.index),paused,detail:scene.details[answers.detail]};world.update(frame-1,config);let timer=setTimeout(()=>world.update(frame,config),paused?0:150);cleanup.set(section,()=>{clearTimeout(timer);world.destroy();});const next=action(body,n===0?'资料看清楚了，看看怎样处理 ↓':'看看整理出的结果 ↓',()=>n===0?runPage(1):result(),{cue:'点这里，继续看后面发生什么'});
if(n===0){const b=node('button','如果资料不对，会怎样？','text-link');b.onclick=()=>{world.update(2,{...config,variant:'issue'});next.disabled=true;const p=node('p',scene.issue,'small');body.insertBefore(p,next);b.textContent='演示确认资料后继续';b.onclick=()=>{p.textContent='示例资料已确认，可以继续处理。';next.disabled=false;world.update(1,config);b.remove();};};body.append(b);}});}
function result(){page(14,'查看结果','最后，你会收到这样的结果',scene.result,body=>{const list=node('div',undefined,'result-cards');chosenObjects(scene,answers).forEach(x=>{const card=node('article');card.append(node('b',x.title));if(answers.delivery==='explained')card.append(node('p','原来：'+x.before));card.append(node('p','现在：'+x.after));list.append(card);});body.append(list);action(body,'结果明白了，看看以后怎么跟进 ↓',followup,{cue:'点这里，看这项工作以后怎样继续'});});}
function followup(){page(15,'继续跟进','下次有变化，接着处理这件事','保留这次记录，后面就不用每次从头解释。',body=>{const demo=node('div',undefined,'visual-demo');demo.append(node('p',scene.improve,'build-summary'));body.append(demo);const feedback=node('div',undefined,'button-row');for(const [v,l]of [['same','同一份资料又来了'],['change','资料有了新变化']]){const b=node('button',l,'secondary');b.onclick=()=>{explain.textContent=v==='same'?'找到上一次的记录，沿用原结果，不再多建一份待办。':'查看新变化，更新原记录。'+scene.improve;};feedback.append(b);}const explain=node('p','可以点击上面两种情况，看看后面会怎样处理。','small');body.append(feedback,explain);action(body,'保存我的搭建说明 ↓',save,{cue:'点这里，把刚才的安排保存下来'});const replay=node('button','↑ 从触发开始，再走一遍','text-link');replay.onclick=()=>{discardAfter(10);start();};body.append(replay,node('p','这是一份需求说明，不会直接启动真实任务。','small'));});}
function save(){const url=URL.createObjectURL(new Blob([planText(makeJourneyPlan(scene,answers))],{type:'text/markdown;charset=utf-8'}));const a=node('a');a.href=url;a.download=`昭回-${scene.id}-搭建说明.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('搭建说明已准备好');}
function browse(){discardAfter(0);$('library').classList.add('open');scrollTo($('library'));}
$('browse').onclick=browse;$('restart').onclick=()=>{discardAfter(0);history.replaceState(null,'',location.pathname);$('library').classList.remove('open');scrollTo($('welcome'));};
function filter(){const q=$('search').value.trim().toLowerCase();const filtered=data.scenes.filter(s=>[s.thought,s.title,s.categoryName].join(' ').toLowerCase().includes(q));$('ideas').replaceChildren(...filtered.map(s=>{const b=node('button');b.type='button';b.dataset.pick=s.id;b.append(node('small',`${String(s.id).padStart(2,'0')} · ${s.categoryName}`),node('span',s.thought));return b;}));$('count').textContent=`${filtered.length} 个想法`;$('empty').hidden=filtered.length>0;}
$('search').oninput=filter;document.addEventListener('click',e=>{const b=e.target.closest('[data-pick]');if(b)select(b.dataset.pick);});
function motion(){document.body.classList.toggle('paused',paused);$('motion').textContent=paused?'开启动效':'暂停动效';$('motion').setAttribute('aria-pressed',String(paused));} $('motion').onclick=()=>{paused=!paused;motion();};filter();motion();
const hash=location.hash.slice(1),initial=hash.match(/^scene-(\d+)$/);if(initial)select(+initial[1]);else if(['compose','presets','stories','improve','capabilities','evidence'].includes(hash)||/^evidence-|^group-/.test(hash))location.replace('./guide.html#'+hash);else if(['reality','platforms','systems','workflows','architecture','onboarding','lab','observability','roadmap','guardrails','research','sources'].includes(hash)||/^source-/.test(hash))location.replace('./architecture.html#'+hash);
