import {SOURCE_NAMES,TRIGGERS,blankAnswers,sampleAnswers,chosenObjects,sourceSteps,setupSteps,makeJourneyPlan,planText,frameStory,StepPlayer} from './journey-model.mjs';
import {createWorld} from './journey-visuals.mjs';
const $=id=>document.getElementById(id), data=JSON.parse($('journey-data').textContent), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let scene,a,step=0,world,revision=1,resolved=false,quiet=false,category='all',paused=matchMedia('(prefers-reduced-motion: reduce)').matches;
const show=(id,yes)=>$(id).hidden=!yes, html=(id,s)=>$(id).innerHTML=s, text=(id,s)=>$(id).textContent=s;
const run=new StepPlayer(renderFrame,{onState:p=>{text('play-toggle',p.playing?'暂停':'继续');world?.setPaused(!p.playing);}});
const build=new StepPlayer(f=>{document.querySelectorAll('.build-list li,.flow-node').forEach((n,i)=>n.classList.toggle('done',i<=f));text('plan-status',setupSteps(scene,a)[f].result);show('start-run-view',f===5);},{interval:1100,onState:p=>text('build-toggle',p.playing?'暂停搭建演示':'继续搭建演示')});
function stop(){run.stop();build.stop();world?.destroy();world=null;}
function select(id){stop();scene=data.scenes.find(s=>s.id===Number(id));if(!scene)return;a=blankAnswers(scene);step=0;revision=1;quiet=false;show('empty-experience',false);show('journey-app',true);$('load-example').disabled=false;text('current-title',scene.thought);text('current-subtitle',scene.title);text('intent-thought',scene.thought);history.replaceState(null,'',`#scene-${String(scene.id).padStart(2,'0')}`);question();$('experience').scrollIntoView({behavior:'instant',block:'start'});}
function phase(p){text('conversation-title',['先把想法说清楚','接好这项工作的资料','按你的要求准备流程','这项工作已经准备好'][p]);$('journey-app').dataset.phase=['clarify','connect','build','run'][p];document.querySelectorAll('[data-phase-label]').forEach((n,i)=>n.classList.toggle('active',i===p));}
function question(){run.stop();build.stop();world?.destroy();world=null;phase(step===2||step===3?1:0);show('question-area',true);show('build-left',false);show('run-left',false);show('planning-view',true);show('runtime-view',false);show('start-run-view',false);show('how-build',false);$('back-answer').disabled=step===0;
const answered=[a.focus!==null?scene.choices[a.focus].label:null,a.detail!==null?scene.details[a.detail]:null,a.source?SOURCE_NAMES[a.source]:null,a.connectionConfirmed?`确认 ${a.shop} 的示例资料`:null,a.trigger?TRIGGERS[a.trigger].label:null,a.delivery?(a.delivery==='brief'?'简明清单':'附上依据和处理建议'):null];
html('chat-history',`<div class="chat-message user">${esc(scene.thought)}</div>`+answered.slice(0,step).map((x,i)=>`<div class="chat-message"><small>昭回 · ${i+1}</small>${esc(['先确认关注范围。','再确认具体处理方式。','资料也在这里一起安排。','核对账号与一份样例。','确认开始条件。','确认结果形式。'][i])}</div><div class="chat-message user">${esc(x||'')}</div>`).join(''));
text('answers-progress',`${step} / 6`);html('intent-choices',answered.filter(Boolean).map(x=>`<p class="intent-line">✓ ${esc(x)}</p>`).join(''));show('connection-preview',step===2||step===3);if(step>=2){text('connection-origin',a.shop);html('connection-preview-steps',sourceSteps(scene,{...a,source:a.source||'existing'}).map(s=>`<li>${esc(s)}</li>`).join(''));}
const buttons=(title,opts)=>`<h3 class="question-title">${esc(title)}</h3>`+opts.map(([v,l])=>`<button type="button" class="answer-button" data-answer="${v}">${esc(l)}</button>`).join('');
let q='';if(step===0)q=buttons(scene.question,scene.choices.map((x,i)=>[i,x.label]));if(step===1)q=buttons(scene.detailQuestion,scene.details.map((x,i)=>[i,x]));if(step===2)q=buttons('这些资料从哪里取得？',Object.entries(SOURCE_NAMES));if(step===3)q=`<h3 class="question-title">先核对店铺和资料</h3><label>本次店铺或平台<select id="shop-choice">${scene.platforms.map(p=>`<option ${p===a.shop?'selected':''}>${esc(p)}</option>`).join('')}</select></label><p>${esc(scene.source)}</p><p class="quiet-note">示例对象：${esc(scene.objects[0])}。实际搭建时在这里核对账号、对象与资料日期。</p>`+buttons('这份样例对应正确吗？',[['yes','样例已核对，继续搭建']]);if(step===4)q=`<label>定时检查时间（北京时间）<input id="check-time" type="time" value="${esc(a.time)}"></label>`+buttons('希望它什么时候开始？',Object.entries(TRIGGERS).map(([k,v])=>[k,v.label]));if(step===5)q=`<label>还有什么要求？（选填）<textarea id="extra-note" maxlength="600" placeholder="例如：先处理主推商品，暂时不催仓库">${esc(a.note)}</textarea></label>`+buttons('希望怎样查看结果？',[['brief','先看简明清单'],['explained','附上依据和处理建议']]);html('question-area',q);html('flow-sketch',setupSteps(scene,a).slice(0,Math.max(1,step)).map((s,i)=>`<div class="flow-node"><small>0${i+1}</small><b>${esc(s.name)}</b><p>${esc(s.place)}</p></div>`).join(''));text('plan-status','每次确认都会写入这项工作的安排。');$('chat-history').scrollTop=$('chat-history').scrollHeight;
}
$('question-area').onclick=e=>{const b=e.target.closest('[data-answer]');if(!b)return;const v=b.dataset.answer;if(step===0)a.focus=+v;if(step===1)a.detail=+v;if(step===2){a.source=v;a.connectionConfirmed=false;}if(step===3){a.shop=$('shop-choice').value;a.connectionConfirmed=true;}if(step===4){a.time=$('check-time').value||'09:00';a.trigger=v;}if(step===5){a.note=$('extra-note').value;a.delivery=v;}step++;if(step===6)startBuild();else question();};
function instructions(){const steps=setupSteps(scene,a);show('how-build',true);html('setup-cards',steps.map((s,i)=>`<article class="setup-card"><small>0${i+1} · ${esc(s.place)}</small><h3>${esc(s.name)}</h3><dl><dt>你来确认</dt><dd>${esc(s.you)}</dd><dt>昭回负责</dt><dd>${esc(s.ai)}</dd><dt>完成后会看到</dt><dd>${esc(s.result)}</dd></dl></article>`).join(''));html('working-principle',`<p>${esc(TRIGGERS[a.trigger].engine)}</p><p>每次围绕${esc(chosenObjects(scene,a).map(x=>x.title).join('、'))}保留来源、进展和待办。下一轮先检查有无变化，再继续原来的记录。</p><p>${esc(scene.improve)}</p>`);}
function startBuild(){run.stop();phase(2);show('question-area',false);show('build-left',true);show('run-left',false);show('planning-view',true);show('runtime-view',false);$('back-answer').disabled=true;const steps=setupSteps(scene,a);html('build-list',steps.map(s=>`<li>${esc(s.name)}</li>`).join(''));html('flow-sketch',steps.map((s,i)=>`<div class="flow-node"><small>0${i+1}</small><b>${esc(s.name)}</b><p>${esc(s.place)}</p></div>`).join(''));instructions();build.start({auto:!paused});}
function runtime(){build.stop();phase(3);show('build-left',false);show('run-left',true);show('planning-view',false);show('runtime-view',true);world?.destroy();world=createWorld($('world-host'),scene);html('run-brief',[["关注范围",scene.choices[a.focus].label],["处理要求",scene.details[a.detail]],["工作资料",SOURCE_NAMES[a.source]+' · '+a.shop],["开始方式",TRIGGERS[a.trigger].label]].map(([k,v])=>`<div class="run-brief-row"><small>${k}</small><p>${esc(v)}</p></div>`).join(''));text('trigger-title',TRIGGERS[a.trigger].label);text('trigger-context',a.trigger==='clock'?`每天 ${a.time}，北京时间`:scene.when);text('trigger-symbol',{clock:'◷',chat:'✉',file:'▤'}[a.trigger]);text('trigger-run',TRIGGERS[a.trigger].action);$('run-variant').value='normal';$('run-variant').options[2].disabled=true;resetRun();}
function resetRun(){run.stop();resolved=false;show('result-panel',false);show('issue-resolution',false);show('feedback-proposal',false);text('frame-number','等待开始');text('frame-title','先触发一份示例输入。');text('frame-description','按你刚才确认的要求，观察资料怎样变成结果。');['play-toggle','run-next','replay-run'].forEach(id=>$(id).disabled=true);world?.update(-1,{paused:true});}
function startRun(){resolved=false;show('result-panel',false);show('issue-resolution',false);show('feedback-proposal',false);['play-toggle','run-next','replay-run'].forEach(id=>$(id).disabled=false);run.start({auto:!paused});}
function renderFrame(f){const variant=$('run-variant').value;const story=frameStory(scene,a,f,{variant,resolved,quiet,duplicate:variant==='duplicate'});world?.update(f,{indices:chosenObjects(scene,a).map(x=>x.index),paused:!run.playing,variant,revision,quiet,detail:scene.details[a.detail],resolved});text('frame-number',`${f+1} / 6`);text('frame-title',story.title);text('frame-description',story.description);html('runtime-rail',['触发','读取','核对','整理','结果','跟进'].map((s,i)=>`<span class="runtime-stop ${i<=f?'active':''}">${s}</span>`).join(''));show('issue-resolution',!!story.blocked);$('run-next').disabled=!!story.blocked||f===5;$('play-toggle').disabled=!!story.blocked||f===5;if(story.blocked){run.pause();text('issue-description',scene.issue);}show('result-panel',f>=4&&!story.blocked);if(f>=4){text('result-title',variant==='duplicate'?'沿用上一次结果':scene.result);text('result-count',`${chosenObjects(scene,a).length} 项`);html('result-records',chosenObjects(scene,a).map(x=>`<div class="result-record"><b>${esc(x.title)}</b>${a.delivery==='explained'?`<small>原来：${esc(x.before)}</small>`:''}<p>${esc(x.after)}</p></div>`).join(''));text('result-detail',scene.details[a.detail]+(quiet?'；未变化的旧记录不重复提醒。':'')+(a.note?'；补充要求：'+a.note:''));$('run-variant').options[2].disabled=false;}}
$('load-example').onclick=()=>{a=sampleAnswers(scene);step=6;startBuild();};$('back-answer').onclick=()=>{step=Math.max(0,step-1);question();};$('build-toggle').onclick=()=>build.toggle();$('build-next').onclick=()=>{build.pause();build.next();};$('start-run-view').onclick=runtime;$('trigger-run').onclick=startRun;$('replay-run').onclick=startRun;$('play-toggle').onclick=()=>run.toggle();$('run-next').onclick=()=>{run.pause();run.next();};$('play-speed').onchange=e=>run.setSpeed(e.target.value);$('run-variant').onchange=resetRun;$('resolve-example').onclick=()=>{resolved=true;show('issue-resolution',false);run.next();};$('return-to-source').onclick=()=>{step=2;question();};$('edit-requirements').onclick=()=>{step=0;question();};$('choose-another').onclick=()=>$('library').scrollIntoView();
document.addEventListener('click',e=>{const b=e.target.closest('[data-pick]');if(b){e.preventDefault();select(b.dataset.pick);}const f=e.target.closest('[data-feedback]');if(f){show('feedback-proposal',true);text('proposal-text',f.dataset.feedback==='noise'?'下一轮把没有变化的内容留在原记录，只突出新变化。':f.dataset.feedback==='wrong'?'下一轮先核实资料，确认后继续整理。':scene.improve);$('apply-proposal').dataset.feedback=f.dataset.feedback;}});
$('apply-proposal').onclick=()=>{const f=$('apply-proposal').dataset.feedback;revision++;quiet=f==='noise';$('run-variant').value=f==='wrong'?'issue':'normal';startRun();};
$('save-plan').onclick=()=>{const url=URL.createObjectURL(new Blob([planText(makeJourneyPlan(scene,a,revision))],{type:'text/markdown;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`昭回-${scene.id}-搭建说明.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function filter(){const q=$('idea-search').value.trim().toLowerCase();let count=0;document.querySelectorAll('.library-card').forEach(card=>{const s=data.scenes.find(s=>s.id===+card.dataset.id);const visible=(category==='all'||s.category===category)&&JSON.stringify([s.thought,s.title,s.platforms,s.source]).toLowerCase().includes(q);card.hidden=!visible;if(visible)count++;});text('library-count',`${count} 个场景`);show('search-empty',!count);document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===category)));}
$('idea-search').oninput=filter;$('idea-search-form').onsubmit=e=>{e.preventDefault();filter();};$('category-filters').onclick=e=>{const b=e.target.closest('[data-category]');if(b){category=b.dataset.category;filter();}};$('reset-search').onclick=()=>{category='all';$('idea-search').value='';filter();};
function motion(){document.body.classList.toggle('motion-paused',paused);$('motion-toggle').setAttribute('aria-pressed',String(paused));text('motion-toggle',paused?'开启动效':'暂停动效');if(paused){run.pause();build.pause();}}
$('motion-toggle').onclick=()=>{paused=!paused;motion();};document.addEventListener('visibilitychange',()=>{if(document.hidden){run.pause();build.pause();}});motion();const initial=location.hash.match(/^#scene-(\d+)$/);if(initial)select(initial[1]);

const legacy=["compose","evidence","reality","lab","sources","platforms","flows"];if(legacy.includes(location.hash.slice(1)))location.replace("./guide.html"+location.hash);
