import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {createPlan,validSelection,readinessFor} from './scene-plan.mjs';
import {planMarkdown,planPrompt} from './scene-export.mjs';

const root=path.dirname(fileURLToPath(import.meta.url));
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const out=path.resolve(root,process.env.QA_OUTPUT || 'qa-output/scenes');
await fs.mkdir(out,{recursive:true});
const checks=[];
const check=(name,value=true)=>{assert.ok(value,name);checks.push(name);};
const bundle=JSON.parse(await fs.readFile(path.join(root,'scenarios.json'),'utf8'));
const scenes=bundle.groups.flatMap(g=>g.scenes);
let server;
let browser;
let page;
let site=process.env.SITE_URL;

try {
  check('Data: 60 distinct contiguous scene identities',scenes.length===60 && scenes.every((s,i)=>s.id===i+1));
  check('Data: every scenario contains situation, evidence, monitoring, output, iteration and human boundary',scenes.every(s=>['ask','moment','inputs','watch','act','deliver','learn','human','metric'].every(k=>typeof s[k]==='string' && s[k].length>=12)));
  check('Data: scene references resolve',scenes.every(s=>s.sources.every(id=>bundle.sources.some(source=>source.id===id))));
  check('Data: scenario titles and sample outcomes are distinct',new Set(scenes.map(s=>s.title)).size===60 && new Set(scenes.map(s=>s.deliver)).size===60);
  const valid=validSelection([1,1,60,'2',0,61,{},null,2.2],scenes);
  check('Plan: invalid persisted identities rejected and duplicates removed',JSON.stringify(valid)==='[1,60]');
  check('Plan: malformed collection safely ignored',validSelection({ids:[1]},scenes).length===0);
  const sample=createPlan(bundle,[1,31],{inputMode:'files',cadence:'daily',goal:'减少重复检查',extra:'额外待评审需求',generatedAt:'2026-09-14T00:00:00Z'});
  check('Plan: export is explicitly a non-activated planning brief',sample.kind==='planning_brief_not_runtime_config' && sample.activated===false && sample.inputs.verified===false && sample.desired_cadence.timer_registered===false);
  check('Plan: business writes and finance are not granted',sample.default_policy.external_business_writes==='deny' && sample.default_policy.financial_execution==='excluded');
  check('Plan: fresh-state scene cannot be promoted by file availability',sample.scenes[1].readiness.code==='offline_snapshot_only');
  check('Plan: declared connector is not proof of verification',readinessFor(scenes[0],'read').code==='connector_verification_required');
  check('Plan: additional requirements do not grant permission',sample.additional_requirement.status==='requires_capability_review_not_authorization');
  check('Plan: Markdown includes iteration and boundaries',planMarkdown(sample).includes('反馈与自我迭代') && planMarkdown(sample).includes(scenes[30].human));
  check('Plan: copied instructions require review before registration',planPrompt(sample).includes('先结合当前昭回已发布能力') && planPrompt(sample).includes('不是运行配置'));
  check('Plan: Markdown escapes user-provided HTML',planMarkdown(createPlan(bundle,[1],{goal:'<img src=x onerror=alert(1)>'})).includes('&lt;img'));
  if(!site){
    const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.md':'text/plain; charset=utf-8'};
    server=http.createServer(async(req,res)=>{
      try {
        const pathname=decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname);
        const target=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));
        if(!target.startsWith(root+path.sep) || pathname.split('/').some(p=>p.startsWith('.'))){res.writeHead(403).end();return;}
        const data=await fs.readFile(target);
        res.writeHead(200,{'Content-Type':types[path.extname(target)] || 'application/octet-stream'});res.end(data);
      } catch {res.writeHead(404).end('Not found');}
    });
    await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
    site=`http://127.0.0.1:${server.address().port}/`;
  }
  try {browser=await chromium.launch({headless:true});} catch {browser=await chromium.launch({headless:true,channel:'chrome'});}
  const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce',acceptDownloads:true});
  page=await context.newPage();
  page.setDefaultTimeout(7000);
  const errors=[];const external=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  page.on('request',r=>{const u=new URL(r.url());if(['http:','https:'].includes(u.protocol)&&u.origin!==new URL(site).origin)external.push(r.url());});
  let response=await page.goto(site,{waitUntil:'networkidle',timeout:45000});
  check('Live page: HTTP 200',response.status()===200);
  check('Live page: correct scene-first edition',(await page.title()).includes('60个国内电商'));
  await page.locator('#scene-count').filter({hasText:'60 / 60'}).waitFor();
  check('Live page: 60 cards, 10 groups and 7 bundles',await page.locator('.scene-card').count()===60 && await page.locator('.scene-group').count()===10 && await page.locator('.preset-card').count()===7);
  check('Live page: 24 evidence records',await page.locator('.source-item').count()===24);
  check('Live page: all internal links resolve',(await page.locator('a[href^="#"]').evaluateAll(links=>links.filter(a=>!document.getElementById(a.hash.slice(1))).map(a=>a.hash))).length===0);
  check('Empty plan cannot export',await page.locator('#export-json').isDisabled() && await page.locator('#export-md').isDisabled());
  for(const [label,width,height] of [['desktop',1440,1000],['tablet',768,1024],['mobile',390,844],['narrow',320,740]]){
    await page.setViewportSize({width,height});
    await page.evaluate(()=>window.scrollTo(0,0));
    check(`${label}: no document horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await page.screenshot({path:path.join(out,`${label}.png`)});
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#day-tab-trading').click();
  check('Day story tabs switch the visible panel',await page.locator('#day-trading').isVisible() && !(await page.locator('#day-opening').isVisible()));
  await page.keyboard.press('ArrowRight');
  check('Day story tabs work with keyboard',await page.locator('#day-tab-review').getAttribute('aria-selected')==='true');
  await page.locator('#day-tab-opening').click();
  for(const g of bundle.groups){
    await page.locator(`.category-filter[data-category="${g.id}"]`).click();
    check(`Category ${g.id}: six relevant records`,await page.locator('.scene-card:visible').count()===6 && await page.locator('.scene-group:visible').count()===1);
  }
  await page.locator('#clear-filters').click();
  await page.locator('#platform-filter').selectOption('小红书');
  check('Platform filter matches scenario metadata',await page.locator('.scene-card:visible').count()===scenes.filter(s=>s.platforms.includes('小红书')).length);
  await page.locator('#clear-filters').click();
  await page.locator('#mode-filter').selectOption('read');
  check('Read-dependent scenes: 12',await page.locator('.scene-card:visible').count()===12);
  await page.locator('#mode-filter').selectOption('file');
  check('File-start scenes: 48',await page.locator('.scene-card:visible').count()===48);
  await page.locator('#scene-search').fill('不存在的需求-0000');
  check('No matches has an explicit empty state',await page.locator('#scene-empty').isVisible() && await page.locator('.scene-card:visible').count()===0);
  await page.locator('#empty-reset').click();
  await page.locator('#scene-search').fill('尺码');
  check('Search finds business situations',await page.locator('.scene-card:visible').count()>0 && await page.locator('.scene-card:visible').count()<60);
  await page.locator('#clear-filters').click();
  await page.locator('.category-filter[data-category="service"]').click();
  await page.locator('#toggle-details').click();
  check('Expand current results affects visible category',await page.locator('.scene-card:visible details[open]').count()===6);
  await page.locator('#toggle-details').click();
  check('Collapse current results works',await page.locator('.scene-card:visible details[open]').count()===0);
  await page.locator('#scene-30 summary').click();
  check('Scenario details include all eight practical dimensions',await page.locator('#scene-30 .scene-field:visible').count()===8);
  await page.locator('[data-scene-id="30"]').screenshot({path:path.join(out,'expanded-scenario.png')});
  await page.locator('[data-add="30"]').click();
  check('Adding a scene updates the plan and dock',await page.locator('#plan-count').innerText()==='1' && await page.locator('#selection-dock').isVisible());
  await page.locator('[data-add="30"]').click();
  check('Same scene toggles off without duplicates',await page.locator('#plan-count').innerText()==='0');
  await page.locator('[data-add="30"]').click();
  await page.locator('[data-preset="solo"]').click();
  check('Preset adds to rather than replacing selection',await page.locator('#plan-count').innerText()==='7');
  await page.locator('[data-preset="solo"]').click();
  check('Repeated preset addition is idempotent',await page.locator('#plan-count').innerText()==='7');
  await page.locator('#plan-goal').fill('我管理两家服饰店，先做清单和草稿。');
  await page.locator('[data-preset="apparel"]').click();
  check('Preset preserves an edited goal',await page.locator('#plan-goal').inputValue()==='我管理两家服饰店，先做清单和草稿。');
  await page.locator('#clear-plan').click();
  await page.locator('#clear-filters').click();
  await page.locator('[data-add="1"]').click();
  await page.locator('[data-add="31"]').click();
  await page.locator('#selected-only').check();
  check('Selected-only filter shows the exact chosen set',await page.locator('.scene-card:visible').count()===2);
  await page.locator('#plan-input').selectOption('files');
  check('File inputs do not mark live-state scenes ready',(await page.locator('#readiness').innerText()).includes('1个时效型场景'));
  await page.locator('#plan-input').selectOption('read');
  check('Declared connection still requires verification',(await page.locator('#readiness').innerText()).includes('已有连接，也要逐场景核验'));
  await page.locator('#plan-input').selectOption('none');
  check('Missing data remains a planning state',(await page.locator('#readiness').innerText()).includes('不是开始运行'));
  await page.locator('#plan-input').selectOption('files');
  await page.locator('#plan-cadence').selectOption('daily');
  await page.locator('#plan-scope').fill('仅店铺A/B的脱敏订单和商品说明');
  await page.locator('.custom-need summary').click();
  await page.locator('#plan-extra').fill('另外想核对仓库交接。');
  await page.locator('#compose .composer').screenshot({path:path.join(out,'plan-builder.png')});
  let downloadPromise=page.waitForEvent('download');
  await page.locator('#export-json').click();
  let download=await downloadPromise;
  const jsonPath=path.join(out,'exported-plan.json');
  await download.saveAs(jsonPath);
  const actual=JSON.parse(await fs.readFile(jsonPath,'utf8'));
  check('JSON export contains actual selection and custom requirements',JSON.stringify(actual.scene_ids)==='[1,31]' && actual.additional_requirement.description==='另外想核对仓库交接。');
  check('JSON export preserves scope and non-activation',actual.scope_description.includes('店铺A/B') && actual.activated===false && actual.desired_cadence.timer_registered===false && actual.default_policy.external_business_writes==='deny');
  check('JSON export retains scene monitoring, iteration and readiness',actual.scenes[1].watch===scenes[30].watch && actual.scenes[1].learn===scenes[30].learn && actual.scenes[1].readiness.code==='offline_snapshot_only');
  downloadPromise=page.waitForEvent('download');
  await page.locator('#export-md').click();
  download=await downloadPromise;
  const mdPath=path.join(out,'exported-plan.md');
  await download.saveAs(mdPath);
  const markdown=await fs.readFile(mdPath,'utf8');
  check('Markdown export has practical fields and evidence',markdown.includes('反馈与自我迭代') && markdown.includes('R12') && markdown.includes('临近发货期限'));
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__copied=text;}}}));
  await page.locator('#copy-brief').click();
  check('Copy action produces a scoped review request',(await page.evaluate(()=>window.__copied)).includes('先结合当前昭回已发布能力'));
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('Permission denied fixture');}}}));
  await page.locator('#copy-brief').click();
  await page.locator('#copy-text').waitFor({state:'visible'});
  check('Clipboard denial has a manual-copy fallback',(await page.locator('#copy-text').inputValue()).includes('不是运行配置'));
  await page.locator('#plan-goal').fill('<img src=x onerror="window.__injected=true">');
  await page.locator('#plan-extra').fill('<script>window.__injected=true</script>');
  check('User text is not executed as HTML',await page.evaluate(()=>window.__injected===undefined));
  const saved=await page.evaluate(()=>Object.fromEntries(Object.entries(localStorage)));
  check('Only scenario IDs are persisted, never free text',Object.keys(saved).length===1 && JSON.stringify(saved).includes('zhaohui.scene-selection.v2') && !JSON.stringify(saved).includes('img') && !JSON.stringify(saved).includes('仓库'));
  await page.locator('[data-remove="1"]').click();
  check('Removing a chosen scene updates selection and filtered library',await page.locator('#plan-count').innerText()==='1' && await page.locator('.scene-card:visible').count()===1);
  await page.locator('a[href="#scene-37"]').first().click();
  check('Deep link reveals a scene hidden by filters',await page.locator('#scene-37').getAttribute('open')!==null && await page.locator('[data-scene-id="37"]').isVisible());
  await page.locator('#evidence-register summary').click();
  await page.locator('#evidence-filter').selectOption('code');
  check('Code evidence filter finds five app references',await page.locator('.source-item:visible').count()===5);
  await page.locator('#evidence-search').fill('无此来源-000');
  check('Evidence search has an empty state',await page.locator('#evidence-empty').isVisible());
  await page.locator('a.evidence-link[href="#evidence-R13"]:visible').last().click();
  check('Citation restores source visibility and opens register',await page.locator('#evidence-R13').isVisible() && await page.locator('#evidence-filter').inputValue()==='all');
  for(const value of ['useful','repeat','wrong']){
    await page.locator(`[data-feedback="${value}"]`).click();
    check(`Feedback branch ${value} changes explanation`,await page.locator(`[data-feedback="${value}"]`).getAttribute('aria-pressed')==='true' && (await page.locator('#feedback-body').innerText()).length>25);
  }
  check('Feedback simulation does not auto-publish a rule',(await page.locator('#feedback-body').innerText()).includes('不自动覆盖正式事实'));
  await page.locator('.feedback-lab').screenshot({path:path.join(out,'feedback-loop.png')});
  await page.reload({waitUntil:'networkidle'});
  check('Reload restores valid selected IDs but not free text',await page.locator('#plan-count').innerText()==='1' && await page.locator('#plan-goal').inputValue()==='');
  await page.evaluate(()=>localStorage.setItem('zhaohui.scene-selection.v2','{"invalid":true}'));
  await page.reload({waitUntil:'networkidle'});
  check('Malformed persisted state does not break page',await page.locator('#plan-count').innerText()==='0' && await page.locator('#export-json').isDisabled());
  await page.evaluate(()=>localStorage.setItem('zhaohui.scene-selection.v2','[1,1,60,999,"2"]'));
  await page.reload({waitUntil:'networkidle'});
  check('Invalid and duplicate persisted IDs are excluded',await page.locator('#plan-count').innerText()==='2');
  await page.locator('#clear-plan').click();
  check('Clear selection removes stored IDs',await page.evaluate(()=>localStorage.getItem('zhaohui.scene-selection.v2')===null));
  await page.setViewportSize({width:390,height:844});
  await page.locator('a[href="#scene-55"]').first().click();
  check('Expanded scenario has no mobile page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.locator('#scene-55').screenshot({path:path.join(out,'mobile-expanded.png')});
  for(const name of ['scenarios.md','scenarios.json','architecture.html','scene-plan.mjs','scene-export.mjs']){
    const result=await context.request.get(new URL(name,site).href);
    check(`Published resource ${name}`,result.status()===200);
    if(name==='scenarios.md')check('Full handout includes final scene and research boundaries',(await result.text()).includes('跑了一个月'));
  }
  const direct=await context.newPage();
  direct.setDefaultNavigationTimeout(10000);
  await direct.goto(new URL('#scene-60',site).href,{waitUntil:'networkidle'});
  check('Direct scene link opens its native details',await direct.locator('#scene-60').getAttribute('open')!==null);
  await direct.goto(new URL('#evidence-R19',site).href,{waitUntil:'networkidle'});
  check('Direct evidence link opens the source register',await direct.locator('#evidence-R19').isVisible());
  await direct.goto(new URL('#lab',site).href,{waitUntil:'networkidle'});
  await direct.waitForURL('**/architecture.html#lab');
  check('Previously shared technical section links remain usable',(await direct.title()).includes('电商自治蓝图'));
  await direct.goto(new URL('#source-E01',site).href,{waitUntil:'networkidle'});
  await direct.waitForURL('**/architecture.html#source-E01');
  check('Previously shared technical evidence links remain usable',await direct.locator('#source-E01').isVisible());
  await direct.close();
  const noJS=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
  const fallback=await noJS.newPage();
  await fallback.goto(site);
  check('All 60 scenarios exist with JavaScript disabled',await fallback.locator('.scene-card:visible').count()===60);
  await fallback.locator('#scene-60 summary').click();
  check('Native scenario disclosure works without JavaScript',await fallback.locator('#scene-60 .field-learn').isVisible());
  await noJS.close();
  const limited=await browser.newContext();
  await limited.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('Storage unavailable fixture');}});});
  const limitedPage=await limited.newPage();
  await limitedPage.goto(site);
  await limitedPage.locator('[data-add="1"]').click();
  check('Selection works even when browser storage is unavailable',await limitedPage.locator('#plan-count').innerText()==='1');
  await limited.close();
  check('No browser errors',errors.length===0);
  check('No third-party or merchant requests',external.length===0);
  const result={result:'passed',scope:'Scene report, local selection and planning exports only; no merchant integration validation',url:site,checks:checks.length,details:checks,browserErrors:errors,externalRequests:external};
  await fs.writeFile(path.join(out,'results.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
} catch(error) {
  if(page){try{await page.screenshot({path:path.join(out,'failure.png')});}catch{}}
  const result={result:'failed',checks:checks.length,details:checks,error:String(error)};
  await fs.writeFile(path.join(out,'results.json'),JSON.stringify(result,null,2));
  console.error(JSON.stringify(result,null,2));process.exitCode=1;
} finally {
  if(browser)await browser.close();
  if(server)await new Promise(resolve=>server.close(resolve));
}
