const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const row=(label,value,i)=>`<div class="record" style="--i:${i}"><span>${esc(label)}</span><strong>${esc(value)}</strong><i aria-hidden="true">↗</i></div>`;
export function sceneMarkup(t,frame,a){
 const [time,title,desc,kind,out]=t.frames[frame];
 const labels=['读取资料','核对事实','提出方案','人工协作','记录结果'];
 const active=Math.min(4,Math.floor(frame*5/t.frames.length));
 const ribbon=`<div class="event-path">${labels.map((s,i)=>`<span class="${i===active?'live':i<active?'done':''}">${i<active?'✓ ':''}${s}</span>`).join('')}</div>`;
 let body='';
 if(kind==='map')body=`<div class="system-map"><div class="map-core">昭回<small>公司工作说明</small></div>${['店铺后台','仓库 / 供货','客服工作','团队记录'].map((v,i)=>`<div class="map-node n${i}"><b>${v}</b><small>保留原系统</small><span class="data-packet">资料 →</span></div>`).join('')}</div>`;
 else if(kind==='chat')body=`<div class="chat-layout"><div class="chat-person"><div class="avatar">${t.id==='member'?'M':'顾'}</div><b>${t.id==='omni'||t.id==='diagnosis'?'老板的追问':'一条真实感业务对话'}</b><small>示例内容 · 不会对外发送</small></div><div class="bubbles"><p class="bubble incoming">${esc(desc)}</p><p class="bubble reply">${esc(out)}</p><div class="typing"><i></i><i></i><i></i><span>依据随回复保留</span></div></div></div>`;
 else if(kind==='table')body=`<div class="data-table"><div class="table-head"><span>业务记录</span><span>本次读取的示例内容</span></div>${t.evidence.map(([k,v],i)=>row(k,v,i)).join('')}<p class="record-note">每条记录保留来源、对象和观察时间。</p></div>`;
 else if(kind==='compare')body=`<div class="comparison"><article><small>原来的资料 / 需要确认</small><h3>${esc(t.evidence[frame%3][0])}</h3><p>${esc(t.evidence[frame%3][1])}</p><span class="flag">等待核对</span></article><div class="transfer">→<i></i></div><article class="verified"><small>核对后 / 本次处理</small><h3>${esc(title)}</h3><p>${esc(out)}</p><span class="flag">保留依据</span></article></div>`;
 else if(kind==='board')body=`<div class="kanban">${['待确认','负责人处理中','保留结果'].map((s,i)=>`<div class="kanban-col"><small>${s}</small><article class="task-card ${i===Math.min(2,Math.floor(frame/3))?'moving active-task':''}"><span>${esc(t.objects[i])}</span><b>${esc(i===0?t.diagnosis[0]:i===1?t.roles[0]:out)}</b><small>${i===0?'保留来源':i===1?(a.size==='small'?'同一位伙伴负责':'主责与协作分开'):'更新原任务，不重复创建'}</small></article></div>`).join('')}</div>`;
 else if(kind==='document')body=`<div class="document-demo"><div class="document-spine">${t.code}<br>草稿</div><article><small>昭回为这家公司准备</small><h3>${esc(title)}</h3><p class="text-line">${esc(desc)}</p><p class="text-line second">${esc(out)}</p><div class="doc-rule"><b>本次要求</b>${esc(t.choices[a.detail]||t.choices[0])}</div><span class="stamp">${a.policy==='shadow'?'观察草稿':'待负责人确认'}</span></article></div>`;
 else if(kind==='content')body=`<div class="content-demo"><div class="video-mock"><div class="shirt"></div><span>LIVE-0915</span><b>棉感针织开衫</b><div class="video-progress"></div></div><div class="content-script"><small>素材 C-12 / 话术核对</small><h3>每句卖点都有出处</h3><p class="deleted">纯棉，适合所有人</p><p class="approved">棉混纺；请参考实测尺寸</p><p>事实 → 脚本草稿 → 人工核验 → 场次记录</p></div></div>`;
 else if(kind==='inventory')body=`<div class="inventory-demo"><div class="warehouse">${Array.from({length:12},(_,i)=>`<div class="box ${i<10?'locked':'available'}" style="--i:${i}">${i<10?'锁定':'可用'}</div>`).join('')}</div><div class="inventory-equation"><b>12</b>实物 − <b>10</b>锁定 = <b class="mint">2</b>可用</div><p>本批需要 5 件，还差 3 件。先核实供货安排。</p></div>`;
 else if(kind==='members')body=`<div class="member-demo">${[['M-01','首购完成','准备有用的服务','eligible'],['M-02','售后处理中','先解决已有问题','hold'],['M-03','已退出联系','不进入联系队列','excluded']].map(([id,s,d,c],i)=>`<article class="member ${c}" style="--i:${i}"><div class="avatar">${id}</div><h3>${s}</h3><p>${d}</p><small>${c==='eligible'?'可核对候选':'本轮排除'}</small></article>`).join('')}</div>`;
 else if(kind==='waterfall')body=`<div class="waterfall">${[['支付',1000],['退款',200],['货品成本',400],['投放',150],['其他费用',100],['经营贡献',150]].map(([l,n],i)=>`<div class="fall-column"><b>${i&&i<5?'−':''}${n}</b><div style="--height:${n/5+18}px;--i:${i}" class="fall-bar f${i}"></div><small>${l}</small></div>`).join('')}</div><p class="record-note">示例口径：未含工资、房租等，不等同净利润。</p>`;
 else if(kind==='chart')body=`<div class="flow-chart">${['同一观察窗口','可归属的业务记录','退款 / 服务反馈','待验证的经营判断'].map((v,i)=>`<div style="--i:${i};--w:${100-i*15}%"><span>${v}</span><b>${['01','02','03','04'][i]}</b></div>`).join('')}</div><p class="record-note">变化不等于因果；没有完整资料时，不显示确定性结论。</p>`;
 else body=`<div class="report-demo"><div class="report-heading"><small>澄禾服饰 · 示例经营日报</small><h3>${esc(t.name)}</h3><span>${esc(time)}</span></div><div class="report-body">${[['已经整理',t.modules[0]],['正在跟进',t.modules[1]],['下一步',t.later]].map(([k,v],i)=>row(k,v,i)).join('')}</div><p class="record-note">${esc(t.metric)}</p></div>`;
 return `<div class="app-window" data-kind="${kind}"><div class="window-chrome"><span class="window-dots">● ● ●</span><span>${esc(t.name)}</span><span class="demo-label">合成业务资料</span></div>${ribbon}<div class="business-stage">${body}</div></div>`;
}
export class Player{
 constructor(host,t,a,{reduced=false,onComplete=()=>{}}={}){this.host=host;this.t=t;this.a=a;this.frame=0;this.running=false;this.timer=null;this.reduced=reduced;this.onComplete=onComplete;this.destroyed=false;this.render();}
 render(){if(this.destroyed)return;const f=this.t.frames[this.frame];this.host.innerHTML=`<div class="play-caption"><span>${esc(f[0])}</span><div><h3>${esc(f[1])}</h3><p>${esc(f[2])}</p></div><b>${this.frame+1} / ${this.t.frames.length}</b></div>${sceneMarkup(this.t,this.frame,this.a)}<p class="frame-result" aria-live="polite">${esc(f[4])}</p><div class="player-controls"><button data-player="prev" ${this.frame===0?'disabled':''}>← 上一步</button><button data-player="play" ${this.frame===this.t.frames.length-1?'disabled':''}>${this.running?'暂停':'播放过程'}</button><button data-player="next" ${this.frame===this.t.frames.length-1?'disabled':''}>下一步 →</button><button data-player="replay">重播</button><label>速度<select aria-label="动画播放速度"><option value="1">正常</option><option value="2" ${this.speed===2?'selected':''}>较快</option></select></label></div><div class="frame-dots">${this.t.frames.map((_,i)=>`<i class="${i<=this.frame?'seen':''}"></i>`).join('')}</div>`;
 this.host.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>{const cmd=b.dataset.player;if(cmd==='play')this.toggle();if(cmd==='next')this.step(1);if(cmd==='prev')this.step(-1);if(cmd==='replay'){this.stop();this.frame=0;this.render();}});this.host.querySelector('select').onchange=e=>{this.speed=+e.target.value;this.schedule();};
 if(this.frame===this.t.frames.length-1)this.onComplete();}
 schedule(){clearTimeout(this.timer);if(this.running&&!this.destroyed)this.timer=setTimeout(()=>{this.frame++;if(this.frame>=this.t.frames.length-1)this.running=false;this.render();this.schedule();},(this.reduced?4500:5200)/(this.speed||1));}
 toggle(){this.running=!this.running;this.render();this.schedule();}
 step(n){this.stop();this.frame=Math.max(0,Math.min(this.t.frames.length-1,this.frame+n));this.render();}
 stop(){this.running=false;clearTimeout(this.timer);}
 destroy(){this.stop();this.destroyed=true;}
}
