import {templates,systems,questions} from './catalog.mjs';
import {initial,recommend,required,readiness,MODES,ruleText,exportText} from './model.mjs';
import {Player,sceneMarkup} from './animation.mjs';
const $=id=>document.getElementById(id), E=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let a=initial(),players=[],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,noticeTimer;
const sources=await fetch('./company/research/sources.json').then(r=>{if(!r.ok)throw Error('研究资料加载失败');return r.json();}).catch(()=>[]);
const chapters=['从一个想法开始','认识你的公司','接好已有系统','形成经营方案','一步一步搭建','看系统如何工作'];
function notify(s){$('notice').textContent=s;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').textContent='',3500);}
function stopPlayers(){players.forEach(p=>p.destroy());players=[];}
function trim(n){stopPlayers();document.querySelectorAll('.step').forEach(el=>{if(+el.dataset.step>=n){observer.unobserve(el);el.remove();}else el.classList.add('past');});}
function scroll(el){el.scrollIntoView({block:'start',behavior:reduced?'instant':'smooth'});}
function setChapter(c){$('chapter-no').textContent=`${String(c+1).padStart(2,'0')} / 06`;$('chapter-name').textContent=chapters[c];$('progress').style.width=`${(c+1)/6*100}%`;$('rail-dots').replaceChildren(...chapters.map((x,i)=>E('i',undefined,i<=c?'done':'')));}
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){setChapter(+e.target.dataset.chapter||0);}}, {rootMargin:'-25% 0px -45% 0px'});observer.observe($('welcome'));
function page(n,chapter,title,desc,render){trim(n);const s=E('section',undefined,'screen step');s.id=`step-${n}`;s.dataset.step=n;s.dataset.chapter=chapter;const wrap=E('div',undefined,'screen-inner');s.append(wrap);const head=E('div',undefined,'screen-heading');head.append(E('p',`${String(n).padStart(2,'0')} / ${chapters[chapter]}`,'eyebrow'),E('h2',title),E('p',desc,'lead'));wrap.append(head);render(wrap,s);const back=E('button','↑ 回看并修改之前的选择','back');back.onclick=()=>scroll(n>1?$(`step-${n-1}`):$('welcome'));wrap.append(back);$('pages').append(s);observer.observe(s);setChapter(chapter);scroll(s);const h=s.querySelector('h2');h.tabIndex=-1;h.focus({preventScroll:true});return s;}
function button(host,text,fn,cls='primary',id){const b=E('button',text,cls);b.type='button';if(id)b.dataset.testid=id;b.onclick=fn;host.append(b);return b;}
function next(host,text,fn){const box=E('div',undefined,'next-action');box.append(E('p','↓ 点击这里，继续下一步','click-cue'));const b=button(box,text+'  →',fn);host.append(box);return b;}
function options(host,list,fn){const grid=E('div',undefined,'choices');list.forEach(([v,title,desc],i)=>{const b=E('button',undefined,'choice');b.dataset.value=v;b.type='button';b.append(E('span',String(i+1).padStart(2,'0'),'choice-no'));const copy=E('div');copy.append(E('b',title));if(desc)copy.append(E('small',desc));b.append(copy,E('span','↘','choice-arrow'));b.onclick=()=>{grid.querySelectorAll('button').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});fn(v);};grid.append(b);});host.append(grid);}
function cards(host,list,cls='info-grid'){const grid=E('div',undefined,cls);list.forEach(([k,v],i)=>{const card=E('article');card.append(E('small',String(i+1).padStart(2,'0')),E('h3',k),E('p',v));grid.append(card);});host.append(grid);return grid;}
function evidenceLinks(host,t){const box=E('details',undefined,'evidence');box.append(E('summary','为什么这样设计？查看调研依据与能力说明'));const p=E('p',t.logic);box.append(p);for(const id of t.sources){const src=sources.find(s=>s.id===id);if(!src)continue;const link=E('a',`${src.publisher} · ${src.title} ↗`);link.href=src.url;link.target='_blank';link.rel='noopener noreferrer';box.append(link,E('small',`${src.access} · ${src.limits}`));}box.append(E('p',`online-agent：${t.maturity}`));host.append(box);}
function ask(key,n){const q=questions.find(q=>q.key===key);page(n,1,q.title,q.desc,body=>options(body,q.options,value=>{a[key]=value;a.detail=0;a.connections={};if(key==='model')ask('size',2);else channels();}));}
function multi(body,list,selected,label,onNext){const form=E('form',undefined,'multi-form');const grid=E('div',undefined,'multi-grid');for(const [id,name,desc]of list){const l=E('label',undefined,'multi-option');const input=E('input');input.type='checkbox';input.value=id;input.checked=selected.includes(id);const text=E('span');text.append(E('b',name));if(desc)text.append(E('small',desc));l.append(input,text);grid.append(l);}form.append(grid);const b=button(form,label+' →',()=>{});b.type='submit';form.onsubmit=e=>{e.preventDefault();const value=[...form.querySelectorAll('input:checked')].map(i=>i.value);onNext(value);};body.append(form);}
function channels(){page(3,1,'公司现在在哪些地方做生意？','选择正在经营的平台。尚未经营的渠道不需要提前接入。',body=>multi(body,['淘宝 / 天猫','拼多多','抖音电商','京东','快手','小红书','微信小店 / 小程序','线下 / 经销商'].map(v=>[v,v,'']),a.channels,'选好了，看看正在用的系统',value=>{if(!value.length){notify('至少选择一个目前经营的平台。');return;}a.channels=value;inventory();}));}
function inventory(){page(4,1,'已有的工具，可以继续用。','选出同事正在用的系统，昭回会先复用它们。只有文件也可以从小范围试起。',body=>{multi(body,systems.map(s=>[s.id,s.name,s.examples]),a.inventory,'确认公司现状',v=>{a.inventory=v;a.connections={};profile();});});}
function profile(){const {primary}=recommend(a);page(5,1,'我先这样理解你的公司。','这份理解来自你的选择；下面的澄禾服饰是用来解释流程的示例公司。',body=>{cards(body,[['经营目标',questions[0].options.find(x=>x[0]===a.goal)[1]],['成交方式',questions[1].options.find(x=>x[0]===a.model)[1]],['团队分工',questions[2].options.find(x=>x[0]===a.size)[1]]]);const line=E('p',`已选渠道：${a.channels.join('、')}。已有系统：${systems.filter(s=>a.inventory.includes(s.id)).map(s=>s.name).join('、')||'先从工作文件与同事说明开始'}。`,'company-summary');body.append(line);const label=E('label','还有什么需要记住？（可不填）','note-label');const input=E('textarea');input.maxLength=600;input.placeholder='例如：先从秋季服饰业务试起，尽量少打扰同事';input.value=a.note;label.append(input);body.append(label);next(body,'理解一致，继续聊',()=>{a.note=input.value.trim();focus();});});}
function focus(){const {primary:t}=recommend(a);page(6,1,t.question,'根据刚才的公司情况，再确认一个会影响方案的选择。',body=>{options(body,t.choices.map((x,i)=>[i,x,'']),v=>{a.detail=+v;connect(0);});});}
function connect(i){const list=required(a),s=list[i],n=7+i;page(n,2,`先接好${s.name}。`,`这一步需要：${s.data}。${a.inventory.includes(s.id)?'你说公司已有这套资料，优先复用。':'这份资料还没有列入现状，可以引导接入，也可以先用文件。'}`,body=>{
 const routes=E('div',undefined,'connection-route');body.append(routes);const detail=E('div');body.append(detail);options(routes,Object.entries(MODES).map(([v,k])=>[v,k,v==='later'?'保留缺口，先看条件式方案':v==='files'?'用一份有日期的示例文件走流程':v==='existing'?'核对原来连接的账号和读取范围':'引导确认账号、范围与一份样例']),route=>{a.connections[s.id]={route,confirmed:false};detail.replaceChildren();
 if(route==='later'){detail.append(E('p',`${s.name}保持待补充。后面的诊断和动画会明确为条件式示例。`,'missing-note'));next(detail,'记住这个缺口，继续',advance);return;}
 if(route==='existing'&&!a.inventory.includes(s.id))detail.append(E('p','现状里没有这套系统；请先确认是否确有可复用连接。此处只演示核对。','missing-note'));
 const w=E('div',undefined,'connect-window');w.append(E('div',`${s.name} / ${route==='files'?'示例资料':'示例连接'}`,'connect-title'));
 const label=E('label',route==='files'?'核对文件日期与用途':'核对账号与公司范围');const sel=E('select');[route==='files'?`${s.name}资料 · 2026-09-15（示例）`:`澄禾服饰 · ${s.name}（示例）`,'另一示例账号 · 需要重新核对'].forEach(v=>{const o=E('option',v);o.value=v;sel.append(o);});label.append(sel);w.append(label,E('p',`仅演示读取：${s.data}`));
 const track=E('div',undefined,'connection-track');track.append(E('span',route==='files'?'工作文件':'公司现有系统'),E('i','→'),E('span','昭回的公司资料'));w.append(track);const sample=E('div',undefined,'sample-record');sample.hidden=true;w.append(sample);detail.append(w);let read=false;
 const b=button(detail,route==='files'?'打开这份示例文件':'演示读取一份资料',()=>{if(sel.selectedIndex===1){sample.hidden=false;sample.textContent='账号不一致。切回澄禾服饰后重新读取，不继续使用这份资料。';read=false;return;}if(!read){read=true;sample.hidden=false;sample.replaceChildren(E('small',route==='files'?'文件快照 · 2026-09-15 09:00，不代表实时资料':'示例试读 · 核对对象与更新时间'),E('b',s.sample));sel.disabled=true;b.textContent='核对无误，使用这份示例资料 →';}else{a.connections[s.id].confirmed=true;advance();}},'primary');
 button(detail,'看看资料过期或连接失败时怎么办',()=>{read=false;a.connections[s.id].confirmed=false;sample.hidden=false;sample.replaceChildren(E('b','读取未成功，不能当作已连接'),E('p','保留已填信息，检查账号与资料日期后重试；也可以改用文件或稍后补充。'));sel.disabled=false;b.textContent='重新读取示例资料';},'text-button');
 });
 function advance(){i+1<list.length?connect(i+1):diagnosis();}
 });}
const start=()=>7+required(a).length;
function diagnosis(){const t=recommend(a).primary,r=readiness(a);page(start(),3,r.missing.length?'资料缺口清楚了，先看怎样分析。':'把资料放在一起，才看得见问题。',r.missing.length?`还缺${r.missing.map(s=>s.name).join('、')}。以下是取得资料后才能验证的示例，不是对你公司的诊断。`:'接下来的发现来自澄禾服饰的合成资料，用来说明昭回会如何分析；不是你公司的真实结论。',body=>{cards(body,t.diagnosis.map((x,i)=>[x,`${t.evidence[i][0]}：${t.evidence[i][1]}`]));body.append(E('p',`本次重点：${t.choices[a.detail]}。${r.files.length?'使用文件的部分保留快照日期，不当成实时状态。':''}`,'company-summary'));evidenceLinks(body,t);next(body,'看昭回怎样制定方案',proposal);});}
function proposal(){const {primary:t,companions}=recommend(a);page(start()+1,3,'这家公司，先这样用上 AI。','先做一套主方案；配套能力按需要逐步加入。你不需要从功能清单里拼装。',body=>{const main=E('article',undefined,'solution-feature');main.style.setProperty('--accent',t.color);main.append(E('p','为你的选择推荐 · 主方案','eyebrow'),E('h3',t.name),E('p',t.promise,'solution-promise'));const why=E('div',undefined,'why');t.reasons.forEach(x=>why.append(E('span','✓ '+x)));main.append(why);body.append(main);cards(body,t.modules.map((x,i)=>[x,t.build[i][1]]));if(companions.length){const p=E('div',undefined,'companions');p.append(E('b','主方案稳定之后，再接上'));companions.forEach(c=>p.append(E('p',`${c.name}：${c.promise}`)));body.append(p);}body.append(E('p',a.size==='small'?'按小团队安排：先一个范围、一个负责人，避免同时开太多工作。':a.size==='company'?'按多部门安排：先统一资料口径，再明确主责、协作和跨部门交接。':'按有分工的团队安排：让运营、客服、仓库在同一项工作里接续处理。','company-summary'));evidenceLinks(body,t);next(body,'按这个方向，一步一步搭建',rules);});}
function rules(){const t=recommend(a).primary;page(start()+2,4,'先告诉昭回，怎样算做好。','把工作重点、确认方式和检查时间放进同一份工作说明。',body=>{cards(body,[['这次先处理',t.choices[a.detail]],['怎样检查结果',t.metric],['遇到这种情况先停下',t.blocker]]);const form=E('form',undefined,'rules-form');const pl=E('label','让 AI 先做到哪一步？');const policy=E('select');for(const[v,l]of[['copilot','准备建议，由负责人确认执行'],['shadow','先观察，只生成分析和草稿']]){const o=E('option',l);o.value=v;policy.append(o);}policy.value=a.policy;pl.append(policy);const tl=E('label','每天几点检查？（北京时间）');const time=E('input');time.type='time';time.required=true;time.value=a.time;tl.append(time);form.append(pl,tl);const b=button(form,'保存示例工作说明，开始搭建 →',()=>{});b.type='submit';form.onsubmit=e=>{e.preventDefault();a.policy=policy.value;a.time=time.value;build(0);};body.append(form);});}
function build(i){const t=recommend(a).primary,[title,desc,out]=t.build[i];page(start()+3+i,4,title,desc,(body,section)=>{const holder=E('div',undefined,'build-stage');const window=E('div',undefined,'app-window');window.append(E('div','昭回 · 正在把方案变成可使用的工作','window-chrome'));const assemble=E('div',undefined,'assembly');t.build.forEach(([name,work,result],j)=>{const card=E('article',undefined,`assembly-card ${j<i?'built':j===i?'building':''}`);card.append(E('span',j<i?'✓':String(j+1).padStart(2,'0')),E('h3',result),E('p',j<=i?work:'后续再搭建'));assemble.append(card);});window.append(assemble);holder.append(window);body.append(holder);const trace=E('div',undefined,'build-detail');trace.append(E('small','这一步完成后，会留下什么'),E('h3',out),E('p',`使用：${required(a).map(s=>s.name).join('、')}。`),E('p',ruleText(a,t)));body.append(trace);const check=E('div',undefined,'build-check');check.hidden=true;body.append(check);const b=button(body,'演示检查这一步的产物',()=>{check.hidden=false;const r=readiness(a);check.replaceChildren(E('b',r.missing.length?'示例结构已准备；真实资料仍待补充':'示例资料与要求已经对应'),E('p',`${out}已经出现在上面的工作台结构中。${r.missing.length?'取得缺少的资料后才能验证真实运行。':'下面继续看工作怎样接续。'}`));b.disabled=true;next(body,i<2?'继续搭建下一部分':'打开搭好的系统，试一次',()=>i<2?build(i+1):run());});});}
function run(){const t=recommend(a).primary,r=readiness(a);page(start()+6,5,'现在，看看它怎样工作。',`按你的要求：${t.choices[a.detail]}。${r.missing.length?'资料尚未齐全，下面播放的是条件式概念演示。':'下面用合成资料模拟一次完整经营过程。'}`,(body,section)=>{
 const focus=E('p',ruleText(a,t),'run-rule');body.append(focus);const mount=E('div',undefined,'player');body.append(mount);const done=next(body,'看结果与下一周安排',followup);done.disabled=true;const p=new Player(mount,t,a,{reduced,onComplete:()=>done.disabled=false});players.push(p);
 const issue=E('div',undefined,'issue-panel');const msg=E('p');msg.hidden=true;const pause=button(issue,'如果资料有问题，会发生什么？',()=>{p.stop();p.render();msg.hidden=false;msg.textContent=t.blocker+' 当前播放暂停，等待核实，不自动越过。';mount.querySelectorAll('button').forEach(b=>b.disabled=true);done.disabled=true;pause.disabled=true;const resume=button(issue,'演示由负责人核实后继续',()=>{msg.textContent='负责人已补充本例所需的示例依据，可以继续核对；真实业务仍以实际资料为准。';pause.disabled=false;resume.remove();p.render();},'secondary');},'text-button');issue.append(msg);body.append(issue);
 });}
function followup(){const {primary:t,companions}=recommend(a),r=readiness(a);page(start()+7,5,'系统搭好之后，工作继续。','老板看到的是结果、原因与下一步；同事继续使用熟悉的业务系统。',body=>{const preview=E('div');preview.innerHTML=sceneMarkup(t,7,a);body.append(preview);cards(body,[['第一周',t.firstWeek],['之后怎样扩大',t.later],['真实落地先补什么',r.missing.length?r.missing.map(s=>s.name).join('、'):'核验真实账号、工具权限和一次完整业务回执']]);const feedback=E('div',undefined,'feedback');const text=E('p','试试下一次资料变化时，系统会怎样接着做。');button(feedback,'同一份资料又来了',()=>text.textContent='查到上次的业务对象与处理记录，沿用原任务；不重复建待办。','secondary');button(feedback,'有了新的业务变化',()=>text.textContent=`重新读取变化，更新原记录。${a.policy==='shadow'?'仍只生成观察草稿。':'需要经营决定的部分继续交给负责人确认。'}`,'secondary');feedback.append(text);body.append(feedback);next(body,'下载这家公司的 AI 化搭建说明',()=>{const url=URL.createObjectURL(new Blob([exportText(a,sources)],{type:'text/markdown;charset=utf-8'}));const link=E('a');link.href=url;link.download=`昭回-${t.name}-搭建说明.md`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('搭建说明已下载。它不会启动真实任务。');});button(body,'换一种老板的选择，再走一遍',restart,'text-button');const l=E('a','阅读完整研究与八套方案 →','research-link');l.href='./company/research.html';body.append(l);});}
function restart(){trim(1);a=initial();$('goal-options').querySelectorAll('button').forEach(b=>b.classList.remove('selected'));setChapter(0);scroll($('welcome'));}
questions[0].options.forEach(([id,title,desc])=>{const b=E('button',undefined,'goal');b.dataset.value=id;b.append(E('span',title),E('small',desc),E('i','↗'));b.onclick=()=>{a=initial();a.goal=id;$('goal-options').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));ask('model',1);};$('goal-options').append(b);});
function motion(){document.body.classList.toggle('reduced',reduced);document.body.classList.toggle('motion-enabled',!reduced);$('motion').textContent=reduced?'开启动效':'减少动效';$('motion').setAttribute('aria-pressed',String(reduced));players.forEach(p=>{p.reduced=reduced;p.stop();p.render();});}
$('motion').onclick=()=>{reduced=!reduced;motion();};$('restart').onclick=restart;document.addEventListener('visibilitychange',()=>{if(document.hidden)players.forEach(p=>{p.stop();p.render();});});motion();setChapter(0);
