import {systemList,goals,modes,branches,chapters,stories,initial,stateAt,exportReport} from './story.mjs';
const $=x=>document.getElementById(x),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let a=initial(),timer,notification; a.motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const art=(name,cls='',alt='')=>`<img class="art ${cls}" src="./paper/assets/${name}.png" alt="${alt}" draggable="false">`;
const button=(label,action,cls='primary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const note=(text)=>`<p class="ink-note">${text}</p>`;
function toast(text){$('notice').textContent=text;clearTimeout(notification);notification=setTimeout(()=>$('notice').textContent='',4500);}
function stop(){clearTimeout(timer);a.playing=false;}
function go(page){stop();a.page=page;render();window.scrollTo({top:0,behavior:'instant'});$('app').querySelector('h1')?.focus({preventScroll:true});}
function heading(title,sub){return `<div class="heading"><p class="eyebrow">${['先说一个想法','让昭回认识你的公司','保留熟悉的系统','把资料接起来','形成公司的经营安排','把公司搭起来','现在，看它怎样运转','把这一天继续下去'][a.page]||''}</p><h1 tabindex="-1">${title}</h1><p>${sub}</p></div>`;}
function choices(items,key){return `<div class="paper-choices">${items.map(([id,title,desc],i)=>`<button class="paper-choice ${a[key]===id?'selected':''}" data-${key}="${id}" aria-pressed="${a[key]===id}" style="--tilt:${i%2?1.3:-1.2}deg"><small>${String(i+1).padStart(2,'0')}</small><strong>${title}</strong>${desc?`<span>${desc}</span>`:''}</button>`).join('')}</div>`;}
function trail(){let c=a.page<2?a.page:a.page<4?2:a.page<6?3:4;$('trail').innerHTML=['说出想法','认识公司','连接系统','搭好公司','看它运转'].map((v,i)=>`<span class="${i<=c?'done':''}">${v}</span>`).join('');}
function back(){return a.page>0?button('回到上一步','back','text-button'):'';}
function render(){document.body.classList.toggle('in-theater',a.page===6);document.body.classList.toggle('reduced',!a.motion);$('motion').textContent=a.motion?'减少动效':'开启动效';$('motion').setAttribute('aria-pressed',String(!a.motion));trail();let html='';
 if(a.page===0){html=heading('你的生意，想先改变什么？','先说一个想法，我们陪你把公司搭起来。')+`<div class="opening-stage">${art('company','opening-company')}${choices(goals,'goal')}${art('mascot','opening-mascot')}<div class="opening-message">${note('昭回 AI<br>和你一起，把想法变成<br>每天接续的经营工作。')}${button('从这个想法开始','next')}</div></div><p class="fine center">你可以改变选择；接下来的方案和第一个故事会跟着变化。</p>`;}
 if(a.page===1){html=heading('先认识，你正在经营的生意。','选择主要成交方式。我们会把它放进后面的经营安排。')+`<div class="question-stage">${art('company','question-art')}${choices(modes,'mode')}<div class="question-bottom">${note('示例公司：澄禾服饰<br>商品、订单与顾客，属于同一家公司的故事。')}${button('这就是我们的经营方式','next')}</div></div>`;}
 if(a.page===2){html=heading('公司已有的工具，继续一起工作。','选出正在使用的系统。没有的部分，可以先用工作文件试跑。')+`<div class="systems-grid">${systemList.map(([id,name,sub,data])=>`<label class="system-slip"><input type="checkbox" value="${id}" ${a.systems.includes(id)?'checked':''}><span><strong>${name}</strong><small>${sub}</small><p>${data}</p></span></label>`).join('')}</div><div class="lower-inline">${art('mascot','small-mascot')}${note('先把资料接好，<br>让 AI 认出同一件商品、同一笔订单。')}${button('带着这些系统，继续','systems')}</div>`;}
 if(a.page===3){html=heading('接入以后，先认准一份资料。','先把商品、订单和库存对应起来，让每次判断用到可靠的资料。')+`<div class="connect-scene">${art('building','connect-art')}<div class="connect-panel"><p class="paper-label">${systemList.filter(x=>a.systems.includes(x[0])).map(x=>x[1]).join(' · ')||'先从商品与订单文件开始'}</p><label class="field">这次怎样取得资料？<select id="method"><option value="existing" ${a.method==='existing'?'selected':''}>复用已有连接</option><option value="new" ${a.method==='new'?'selected':''}>引导连接公司系统</option><option value="files" ${a.method==='files'?'selected':''}>使用有日期的工作文件</option></select></label><div class="paper-record"><small>${a.connected?'示例资料核对完成':'等待试读一份示例资料'}</small><strong>KN-2401 · 米白开衫</strong><p>店铺商品 TB-36 / 仓库编码 KN-2401-M</p><p>${a.connected?'来源已对应 · 观察时间 09:00 · 公司范围一致':'需要确认：同款、同色、同尺码、同一公司'}</p></div>${button(a.connected?'资料一致，形成经营安排':'演示读取并核对一份资料',a.connected?'next':'connect')}${button('试试账号不一致或资料过期','connect-fail','text-button')}</div></div>`;}
 if(a.page===4){const first=a.goal==='team'?'delay':a.goal==='product'?'care':'launch';html=heading('这家公司，开始一起往前走。','先形成持续经营的安排，再让已有系统接续每次变化。')+`<div class="plan-strip"><span>经营方向：${goals.find(g=>g[0]===a.goal)[1]}</span><span>成交方式：${modes.find(g=>g[0]===a.mode)[1]}</span></div><div class="plan-world">${art('building','plan-art')}${art('mascot','plan-mascot')}<div class="plan-notes">${[['主动创造生意','需求出现，查货盘、做内容、启动验证。'],['协调销售与供货','订单、库存、推广和交期一起调整。'],['让反馈改进经营','顾客问题带动内容与服务一起修正。']].map(([t,d])=>`<article class="paper-record"><strong>${t}</strong><p>${d}</p></article>`).join('')}</div></div><div class="lower-inline">${note(`从“${stories[first].short}”开始看。<br>日常动作自主推进，结果带着依据回来。`)}${button('把这套安排搭起来','next')}</div>`;}
 if(a.page===5){let names=['认识同一件商品','记住公司的做法','接续每一次变化'];html=heading('把熟悉的系统，接成一支经营团队。','每完成一部分，就留下可继续使用的资料和工作方法。')+`<div class="build-tabs">${names.map((n,i)=>`<div class="paper-record ${i===a.build?'active':''}"><strong>${n}</strong><span class="stamp">${i<a.build?'已准备':i===a.build?'试跑中':'随后搭建'}</span></div>`).join('')}</div><div class="build-world">${art('building','build-art')}<div class="book-facts">${[['店铺 TB-36','仓库 KN-2401-M'],['先保成交订单','现货才可承诺'],['供货延期 3 天','接续 3 项动作']][a.build].map((x,i)=>`<span style="--delay:${i*250}ms">${x}</span>`).join('')}</div>${art('mascot','build-mascot')}<div class="build-evidence paper-record"><small>本步留下什么</small><strong>${['公司商品地图','经营工作说明','可接续的事件记录'][a.build]}</strong><p>${['TB-36 与 KN-2401-M 对应；未知映射保留待核实。','记住经营目标、可靠来源、操作范围和停止条件。','库存变化后核对订单；重复事件沿用原记录，不重复执行。'][a.build]}</p></div></div><div class="lower-inline">${note(['先认准事实，才让工作接起来。','AI 知道怎样做，也知道什么时候要停。','试跑：事件变化 → 判断 → 操作 → 回读结果。'][a.build])}${button(a.build<2?'核对完成，搭建下一部分':'试跑完成，看它开始工作','build')}</div>`;}
 if(a.page===6)html=player();
 if(a.page===7){const v=stateAt(a);html=heading('你给方向，它把工作持续往前推。','老板看见动作、结果和还没解决的事情。下一次变化，会接续原来的工作。')+`<div class="finish-world">${art('company','finish-company')}${art('mascot','finish-mascot')}<div class="finish-copy"><p class="eyebrow">刚才的经营故事</p><h2>${v.s.short}</h2><p>${v.result}</p><div class="paper-record"><strong>下一步，仍会继续</strong><p>${v.s.pending}</p></div>${button('换一个事件，看看不同走向','replay-stories')}${button('下载这一段经营记录','download','text-button')}</div></div><div class="fine center">本例按系统职责推导，未接入真实业务平台；动画不代表经营收益已经验证。</div>`;}
 $('app').innerHTML=`<section class="scene page-${a.page}">${html}${back()}</section>`;bind();}
function player(){const v=stateAt(a),{s}=v;return heading(s.title,s.lead)+`<div class="story-select">${Object.values(stories).map(s=>`<button data-story="${s.id}" class="${s.id===a.story?'active':''}" aria-pressed="${s.id===a.story}">${s.short}</button>`).join('')}</div><div class="theater frame-${a.frame} branch-${a.branch}">
 <div class="trigger-region">${art(s.asset,'trigger-art')}<div class="trigger-slip paper-record"><small>${s.source}</small><strong>${s.trigger}</strong><p>${s.triggerNote}</p></div></div>
 <div class="fact-region ${a.frame>=1?'revealed':''}">${s.facts.map(([k,val],i)=>`<div class="fact-slip paper-record" style="--delay:${i*160}ms"><small>${k}</small><strong>${a.branch==='missing'&&!a.resolved&&i===0?'资料待核实':val}</strong></div>`).join('')}</div>
 <div class="ai-region ${a.frame>=2?'thinking':''}">${art('mascot','theater-mascot')}<strong>昭回 AI</strong><p>${a.frame>=2?v.narration:'变化已经发生，昭回正在读取资料。'}</p>${a.frame>=2?button('看看判断依据','evidence','text-button'):''}</div>
 <div class="action-region ${a.frame>=3?'revealed':''}">${art('paths',`decision-paths ${a.frame>=3?'revealed':''}`)}${v.actions.map((x,i)=>`<div class="action-slip paper-record ${v.statuses[i]==='已确认'?'confirmed':''}" style="--delay:${i*230}ms">${art(['megaphone','calendar','customer'][i],'action-object')}<small>${x[0]} · ${x[1]}</small><strong>${x[2]} <span class="arrow">→</span> <em>${x[3]}</em></strong><span class="receipt">${v.statuses[i]}${v.statuses[i]==='已确认'?` · ${s.ids[i]} 模拟回执`:''}</span></div>`).join('')}</div>
 <div class="human-region ${a.branch==='human'&&a.frame>=2?'visible-human':''}">${art('hand','human-hand')}<div class="human-copy"><p>${a.intervention==='pause'?'老板：暂停，先核实再继续。':s.human}</p><div>${button('按这个要求继续','human-adjust','blue-button')}${button('暂停后续动作','human-pause','text-button')}</div></div></div>
 <div class="chapter-caption"><span>${String(a.frame+1).padStart(2,'0')} / ${chapters[a.frame]}</span><p>${a.frame>=5?v.result:a.frame<2?v.narration:a.frame===2?s.explain:v.blocked?'未取得依据或回执的动作保持等待；已经完成的操作不会被假装撤回。':a.frame===3?'逐项提交动作，并等待各系统返回结果。':'确认生效的动作才计入完成；后续经营效果仍需观察。'}</p></div></div>
 <div class="branch-picker"><span>换一种情况，故事会怎样？</span>${branches.map(([id,name])=>`<button data-branch="${id}" class="${a.branch===id?'active':''}" aria-pressed="${a.branch===id}">${name}</button>`).join('')}</div>
 ${v.blocked?`<div class="block-note"><p>${v.narration}</p>${button(a.branch==='human'?'老板允许，恢复后续工作':a.branch==='missing'?'演示补齐资料，再继续':'核对原记录，补做未完成动作','resolve','blue-button')}</div>`:''}
 <div class="playbar">${button(a.playing?'暂停':'播放过程','play','play-button',v.blocked||a.frame===5?'disabled':'')}<div class="scrubber"><input aria-label="动画进度" type="range" id="seek" min="0" max="5" step="1" value="${a.frame}"><div>${chapters.map((c,i)=>`<button data-frame="${i}" class="${i<=a.frame?'seen':''}">${c}</button>`).join('')}</div></div>${button('上一步','prev-frame','text-button',a.frame===0?'disabled':'')}${button('下一步','next-frame','text-button',a.frame===5||v.blocked?'disabled':'')}${button('重播','restart-story','text-button')}<label class="speed">速度<select id="speed"><option value="1" ${a.speed===1?'selected':''}>正常</option><option value="2" ${a.speed===2?'selected':''}>较快</option></select></label></div>${a.frame===5?`<div class="center">${button('看看最终成果与后续安排','finish')}</div>`:''}`;}
function schedule(){clearTimeout(timer);if(!a.playing)return;timer=setTimeout(()=>{if(a.frame<5)a.frame++;if(a.frame===5||stateAt(a).blocked)a.playing=false;render();schedule();},6000/a.speed);}
function showInfo(html){stop();if(a.page===6)render();$('info-body').innerHTML=html;$('info').showModal();}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));for(const key of ['goal','mode'])document.querySelectorAll(`[data-${key}]`).forEach(b=>b.onclick=()=>{a[key]=b.dataset[key];render();});document.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>{stop();a.story=b.dataset.story;a.intervention='adjust';a.pausedStatuses=null;a.frame=0;a.resolved=false;render();});document.querySelectorAll('[data-branch]').forEach(b=>b.onclick=()=>{stop();a.branch=b.dataset.branch;a.pausedStatuses=null;a.frame=0;a.resolved=false;a.intervention='adjust';render();});document.querySelectorAll('[data-frame]').forEach(b=>b.onclick=()=>seek(+b.dataset.frame));$('seek')?.addEventListener('input',e=>seek(+e.target.value));$('speed')?.addEventListener('change',e=>{a.speed=+e.target.value;schedule();});$('method')?.addEventListener('change',e=>{a.method=e.target.value;a.connected=false;render();});}
function seek(n){stop();a.frame=n;if(stateAt(a).blocked&&n>3)a.frame=3;render();}
function act(action){switch(action){case'next':if(a.page===4)a.build=0;go(a.page+1);break;case'back':go(Math.max(0,a.page-1));break;case'systems':a.systems=[...document.querySelectorAll('.system-slip input:checked')].map(x=>x.value);a.connected=false;if(!a.systems.length)a.method='files';go(3);break;case'connect':a.connected=true;render();toast('示例公司范围、商品映射和时间已核对。');break;case'connect-fail':a.connected=false;render();toast('账号或时间不一致：本次资料不能使用，请重新读取。');break;case'build':if(a.build<2){a.build++;render();}else{a.story=a.goal==='team'?'delay':a.goal==='product'?'care':'launch';a.frame=0;a.branch=a.systems.length<3?'missing':'normal';a.resolved=false;go(6);}break;case'play':a.playing=!a.playing;render();schedule();break;case'prev-frame':seek(a.frame-1);break;case'next-frame':seek(a.frame+1);break;case'restart-story':stop();a.pausedStatuses=null;a.intervention='adjust';a.frame=0;a.resolved=false;render();break;case'resolve':a.resolved=true;if(a.branch==='human')a.intervention='adjust';render();break;case'human-pause':a.pausedStatuses=stateAt(a).statuses;stop();a.intervention='pause';if(a.frame<3)a.frame=3;render();break;case'human-adjust':a.intervention='adjust';render();break;case'finish':go(7);break;case'replay-stories':go(6);break;case'evidence':{const v=stateAt(a);showInfo(`<h2>昭回根据什么判断？</h2><p>${v.s.explain}</p>${v.s.facts.map(x=>`<div class="paper-record"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}<p>平台事件、定期查询和工作文件都可以带来变化；本例为合成资料，不把所有来源称为实时。</p><p>经营要求：${goals.find(x=>x[0]===a.goal)[1]}。成交方式：${modes.find(x=>x[0]===a.mode)[1]}。</p>`);break;}case'download':{const url=URL.createObjectURL(new Blob([exportReport(a)],{type:'text/markdown;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='昭回-纸艺经营记录.md';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出本次选择、判断与模拟执行记录。');break;}}}
$('motion').onclick=()=>{a.motion=!a.motion;render();};$('home').onclick=()=>{stop();const motion=a.motion;a=initial();a.motion=motion;go(0);};$('about').onclick=()=>showInfo(`<h2>故事背后的系统</h2><p>AI 已经连接公司系统，在既定经营要求内持续工作。这里按职责推导能力，未声称具体产品已经接通。</p><div class="system-explain">${systemList.map(x=>`<article><h3>${x[1]}</h3><small>${x[2]}</small><p>${x[3]}</p></article>`).join('')}</div><p>财务、税务系统不在本版范围。研发、打样、质检等实物工作由对应团队完成，AI 负责组织和跟进。</p><a href="./company/research.html">阅读经营研究与来源</a>`);$('info').querySelector('.close').onclick=()=>$('info').close();$('info').addEventListener('click',e=>{if(e.target===$('info'))$('info').close();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();if(a.page===6)render();}});render();
