export const systemList=[['shop','店铺与订单','ERP · OMS','商品、订单、取消与履约'],['product','商品与内容','PIM · 设计工具','规格、材质、素材和版本'],['supply','供应与仓库','SCM · WMS · TMS','可用量、在途、交期与揽收'],['growth','营销与投流','活动 · 推广','商品、素材、预算与结果'],['service','顾客与服务','客服 · SCRM','咨询、售后与服务记录'],['work','研发与协作','PLM · PMS · 钉钉 / 飞书','样品、任务、依赖和反馈']];
export const goals=[['grow','让生意自己往前走','主动发现机会，推进试卖与增长'],['team','让团队少些重复工作','让订单、供货和服务一起接续'],['product','让好商品被更多人看见','把顾客需求变成商品与内容']];
export const modes=[['shelf','搜索、商城与商品卡'],['content','内容、直播与达人'],['mixed','多种渠道一起经营']];
export const branches=[['normal','自动处理'],['missing','资料不足'],['failed','操作失败'],['human','人工介入']];
export const chapters=['事件触发','读取事实','作出判断','跨系统处理','核验结果','继续经营'];
export const stories={
 delay:{id:'delay',title:'一批货晚到了，接下来会发生什么？',short:'供货延期',lead:'一个交期变化，牵动推广、活动和客服。',asset:'truck',source:'SCM · 供货更新',trigger:'周三到货 → 周六到货',triggerNote:'PO-81 · 补货 80 件延期 3 天',facts:[['WMS · 现货','48 件可用'],['OMS · 订单','12 单已锁定'],['SCM · 在途','80 件未入库']],decision:'先保住已成交订单，再调整推广。',explain:'48 件是扣除锁定后的可用量；12 单已有库存保障。在途未入库，不能拿来承诺销售。',actions:[['投流','AD-81 · 日预算','¥260','¥100'],['营销','周四扩量活动','准备参加','暂缓'],['客服','补货交期说明','原周三','预计周六，待核实']],ids:['AD-81','ACT-81','KB-81'],result:'推广与活动已调整，供货仍在跟进。',pending:'待 80 件实际入库后重算供给；已有订单继续检查揽收。',missing:'仓库资料已过期，48 件不能当作当前可用库存。',recovery:'重新读取 WMS，确认当前可用 48 件，12 单锁定状态仍有效。',failure:'投流调整未取得回执。活动与客服已更新，不能把推广也标成成功。',human:'老板：先别降投放，只卖现货。',humanDecision:'重新核对有货规格，保留现货推广，停止缺货规格的新增投放。',humanActions:[['投流','AD-81 · 推广范围','全部规格','仅有货规格'],['营销','周四扩量活动','准备参加','暂缓'],['客服','补货交期说明','原周三','预计周六，待核实']],humanResult:'按老板的新要求，只推广有货规格。'},
 launch:{id:'launch',title:'顾客的一句话，怎样变成一款新商品？',short:'发现新品机会',lead:'从已有货盘中验证需求，让商品真正开始经营。',asset:'shirt',source:'客服 · 顾客需求',trigger:'“有没有长一点的款式？”',triggerNote:'近 7 天 · 18 位不同顾客提出相似需求',facts:[['PIM · 候选','长版衬衫'],['SCM · 素材','样品已确认'],['WMS · 现货','40 件可试卖']],decision:'先用现有商品小范围试卖，验证需求。',explain:'有确认规格、实拍素材与现货；不虚构一天完成新品研发和生产。初期销量不能证明持续需求。',actions:[['PIM / 店铺','CS-2609 · 商品','未上架','长版衬衫上架'],['设计 / 内容','CONTENT-09','已确认素材','详情图与脚本生成'],['投流','EXP-09 · 实验','未开始','限额 ¥300 试卖']],ids:['SHOP-609','CONTENT-09','EXP-09'],result:'商品已上架，内容已生成，试卖已开始。',pending:'接续访问、订单和退款窗口；获得足够依据后再决定是否扩大。',missing:'候选商品的材质存在两个版本，不能据此制作卖点或直接上架。',recovery:'读取已确认的商品版本：棉混纺、衣长 72cm，并记录依据。',failure:'店铺上架没有返回成功。内容已经生成，推广暂不启动。',human:'老板：先不卖，保留内容，等样品复核。',humanDecision:'保留已生成内容，暂停商品上架和试卖，等待样品复核结果。',humanActions:[['PIM / 店铺','CS-2609 · 商品','准备上架','暂不上架'],['设计 / 内容','CONTENT-09','已生成','保留草稿'],['投流','EXP-09 · 实验','待启动','暂不投入']],humanResult:'内容成果保留，试卖等待样品复核。'},
 care:{id:'care',title:'一句“和描述不一样”，让整套内容改起来。',short:'顾客反馈改进',lead:'把反馈追到具体版本，再跟进修改和顾客服务。',asset:'skirt',source:'客服 · 售后反馈',trigger:'“视频说纯棉，标签不是。”',triggerNote:'VOC-31 · 6 位顾客提到材质预期不符',facts:[['PIM · 成分','65% 棉 / 35% 聚酯'],['内容 · 字幕','旧版写“纯棉”'],['OMS · 商品','SK-3102 半裙']],decision:'先停止错误表达，再同步内容与服务。',explain:'确认资料与视频字幕存在冲突，先修正该版本；不能仅凭这条反馈认定所有批次都有质量问题。',actions:[['投流','POST-31 · 旧素材','继续推广','暂停使用'],['设计 / 内容','POST-31B · 新版','“纯棉”','“棉混纺”'],['客服','成分问答','沿用旧素材','引用成分卡 v2']],ids:['AD-31','POST-31B','KB-31'],result:'旧素材暂停，新版内容与服务知识已更新。',pending:'继续处理 2 位顾客的售后；同类反馈是否减少，留到后续观察。',missing:'尚未找到已确认的成分资料，不能用另一句未经核实的话替换旧文案。',recovery:'取得 PIM 已确认成分卡 v2：65% 棉、35% 聚酯纤维。',failure:'旧素材暂停未取得回执。新版内容保留待用，继续核实旧素材状态。',human:'老板：先暂停发布，等商品同事确认。',humanDecision:'保留修订草稿，先停止旧素材推广；新内容等待商品事实确认。',humanActions:[['投流','POST-31 · 旧素材','继续推广','暂停使用'],['设计 / 内容','POST-31B · 新版','准备发布','保留待确认'],['客服','成分问答','确定性答复','先核实，不沿用旧说法']],humanResult:'停止旧素材扩散，新版等待商品确认。'}
};
export function initial(){return {page:0,goal:'grow',mode:'mixed',systems:systemList.map(x=>x[0]),method:'existing',connected:false,build:0,story:'delay',branch:'normal',frame:0,resolved:false,intervention:'adjust',playing:false,speed:1,motion:true};}
export function stateAt(a){const s=stories[a.story],human=a.branch==='human',pause=human&&a.intervention==='pause';const blocked=a.frame>=3&&((['missing','failed'].includes(a.branch)&&!a.resolved)||pause);let actions=human?s.humanActions:s.actions;let narration=[s.triggerNote,'把来源、商品和更新时间放在一起核对。',s.decision,'开始把判断落实到各系统。','逐项读取执行结果，不把提交当成成功。',s.pending][a.frame];
 if(a.branch==='missing'&&a.frame>=2)narration=a.resolved?s.recovery:s.missing;
 if(a.branch==='failed'&&a.frame>=3)narration=a.resolved?'已核对原记录，只补做未完成动作，不重复执行已成功的操作。':s.failure;
 if(human&&a.frame>=2)narration=pause?'老板要求暂停：不再提交后续动作，保留已有事实和进度。':s.humanDecision;
 const statuses=actions.map((_,i)=>{if(a.frame<3)return '未执行';if(pause)return a.pausedStatuses?.[i]==='已确认'?'已确认':a.pausedStatuses?.[i]==='草稿保留'?'草稿保留':a.pausedStatuses?.[i]==='已提交'?'待核实':'等待';if(a.branch==='missing'&&!a.resolved)return '等待';if(a.branch==='failed'&&!a.resolved)return a.story==='delay'&&i>0||a.story==='launch'&&i===1?'已确认':a.story==='launch'&&i===2||a.story==='care'&&i>0?'等待':'待核实';if(human&&a.story==='launch')return i===1?'草稿保留':'等待';if(human&&a.story==='care'&&i===1)return '等待';return a.frame>=4?'已确认':'已提交';});
 return {s,actions,statuses,blocked,narration,result:blocked?'工作保留在这里，等待核实后接续。':human?s.humanResult:s.result,receiptCount:statuses.filter(x=>x==='已确认').length};}
export function exportReport(a){const v=stateAt(a);return ['# 昭回 · 纸艺经营演示记录','合成资料与模拟回执；未操作真实业务系统。',`经营目标：${goals.find(x=>x[0]===a.goal)[1]}`,`经营方式：${modes.find(x=>x[0]===a.mode)[1]}`,`已有系统：${systemList.filter(x=>a.systems.includes(x[0])).map(x=>x[1]).join('、')||'暂无，按文件试跑'}`,`资料方式：${a.method}`,`事件：${v.s.title}`,`分支：${branches.find(x=>x[0]===a.branch)[1]}`,`当前阶段：${chapters[a.frame]}`,`判断：${v.narration}`,...v.actions.map((x,i)=>`- ${x[0]} / ${x[1]}：${x[2]} → ${x[3]}；${v.statuses[i]}`),`结果：${v.result}`,`后续：${v.s.pending}`].join('\n');}
